### ISSUE TITLE
/sys/class/backlight/intel_backlight/actual_brightness: No such file or directory

### ISSUE THREAD

**Issue by elioth010** [vjay82/Linux-i915-Backlight-Control#1]
when run the script to set the value on screen
$/usr/local/bin/intelBrightness minus
/usr/local/bin/intelBrightness: line 58: /sys/class/backlight/intel_backlight/actual_brightness: No such file or directory
Setting new value: 0x3A90000

**Comment by vjay82** [comment]
fixed
