### ISSUE TITLE
Where should I set own value for max brightness

### ISSUE THREAD

**Issue by tjespe** [vjay82/Linux-i915-Backlight-Control#2]
README.md says "intelBrightness - [...] Warning I hardcoded the max brightness value my card had into the script. You should get the value from /sys/class/backlight/intel_backlight/max_brightness while the kernel's driver is still in place and modify this script."

I fount my value in `/sys/class/backlight/intel_backlight/max_brightness`, but I did not understand where in the script to write it. Could you maybe add this to the README.md?

**Comment by vjay82** [comment]
Hi, I had not used or touched the code since then. I don't even have the laptop I needed it for anymore. 

This looks like an upper boundary:

if ! [[ "937" -ge "${currentValueInt}" ]] ; then
 currentValueInt=937
fi

Sorry for the poor documentation.
